### ISSUE TITLE
Can't take the input from S3

### ISSUE THREAD

**Issue by soumyadip007** [bitmovin/bitmovin-java#94]

**Comment by SInCE** [comment]
Hi @soumyadip007, 

Please make sure that your Access/Secret Key pair comes with sufficient rights to access the file on your S3 bucket. More details about the minimum IAM policy required can be found in our documentation here: https://bitmovin.com/docs/encoding/faqs/how-do-i-create-a-aws-s3-bucket-which-can-be-used-as-output-location

---

If you need help with your input/output configuration of your account you can reach out to our support team in your Bitmovin Dashboard here: https://bitmovin.com/dashboard/support/cases/create

Thank you very much and have a great day :)

**Comment by soumyadip007** [comment]
Thanks @SInCE
